# %% [markdown]
# ## Stage 5: Gaps (what the pipeline could not find, and what would find it)
#
# **Choice:** gaps are generated by code from the run itself: every (document, signal) that is NOT_FOUND, PARTIAL, UNVERIFIED or low-confidence, every signal no document supports,
# every unresolved conflict, plus *structural* gaps that hold whatever the extraction says (there is no industry code for fractional CFO; no report gives a niche share).
# Each gap says what is missing and names a *type* of source that could fill it. **Those suggested sources were not consulted**; they come from general knowledge of where such data lives, not from the three reports.
#
# **Alternative rejected:** a generic "limitations" paragraph. It would read the same whatever the run found, and it would not tell a founder which number to go and get.

# %%
SIGNAL_SOURCES = {
    "S1": "A report on a closer proxy than all management consulting or all accounting. Census Bureau Economic Census / Nonemployer Statistics receipts for NAICS 541611 and 541219 (census.gov/naics for the code, data.census.gov for the tables), and IBISWorld 'financial management consulting' segment data.",
    "S2": "No report here gives a niche share. Look for a vendor report on outsourced / virtual / fractional CFO or 'bookkeeping and advisory' services (existence not confirmed; not searched), Census Economic Census concentration ratios (top-4/8/20/50 share) by NAICS, or bottom-up counts from state CPA-society firm directories and LinkedIn / Google Business listings.",
    "S3": "Primary law, not industry reports: each target state's Board of Accountancy rules on who may use 'CPA' and offer attest vs non-attest services; AICPA independence rules; state consumer-privacy statutes. Ask a licensed CPA or attorney whether fractional CFO advice needs a licence.",
    "S4": "BLS Occupational Employment and Wage Statistics for financial managers and accountants by state; accounting-software vendor market-share studies (QuickBooks, Xero, NetSuite class); AICPA firm-staffing surveys on CPA supply.",
    "S5": "Census Statistics of U.S. Businesses (SUSB) receipts-size tables and SBA Office of Advocacy small-business profiles for the $2M-$20M revenue band; a buyer survey (owners' willingness to pay for part-time finance leadership).",
    "S6": "Primary research: interviews with 5-10 fractional CFOs and 5-10 SMB owners; AICPA / accounting-trade surveys on advisory demand.",
    "S7": "Primary research plus a review of platform-based competitors' public pricing and positioning (not in these reports).",
}

def stage5_gaps(extractions, verified, records, docs, naics=None, chosen=None):
    naics, chosen = naics or NAICS, chosen or CHOSEN_CODE
    gaps = []
    for d, ext in extractions.items():
        for s in ext["signals"]:
            v = verified[d][s["signal_id"]]
            reasons = []
            if v["status_final"] != "FOUND": reasons.append(v["status_final"])
            if s["confidence"]["level"] == "low": reasons.append("low confidence")
            if v["numbers_unmatched"]: reasons.append("numbers not in quotes")
            if reasons:
                gaps.append({"scope": "document-signal", "signal_id": s["signal_id"], "doc_id": d, "why": " + ".join(reasons),
                             "what_is_missing": s["notes"], "what_would_find_it": SIGNAL_SOURCES[s["signal_id"]]})
    for sid, r in records.items():
        if r["primary"] is None:
            gaps.append({"scope": "signal", "signal_id": sid, "doc_id": None, "why": "no document supports this signal",
                         "what_is_missing": "Every report returned NOT_FOUND or UNVERIFIED.", "what_would_find_it": SIGNAL_SOURCES[sid]})
        for c in r["conflicts"]:
            if c["kind"] not in ("value_disagreement_same_industry_family", "within_document"):
                continue        # rating and share-basis differences are explained by scope (kept in the brief), not unresolved
            gaps.append({"scope": "conflict", "signal_id": sid, "doc_id": None, "why": f"unresolved conflict: {c['metric']}",
                         "what_is_missing": "Values differ: " + "; ".join(f"{s['doc_id']} = {s['value']}" for s in c["sides"]) + ". " + c["why_they_may_differ"],
                         "what_would_find_it": "The publisher's methodology note (IBISWorld / First Research analyst support) or a primary statistical source such as the Census Economic Census."})
    exts = extractions
    rel = "; ".join(f"{d}: {e['report_scope']['relation_to_chosen_naics']}" for d, e in exts.items())
    dates = ", ".join(f"{d} = {docs[d]['publication_date']}" for d in exts)
    structural = [
        ("No industry code for fractional CFO", f"Fractional CFO has no NAICS code, so every number in this brief describes a PROXY industry (chosen: {chosen}, "
         f"{naics['entries'][chosen]['title']}). Growth, size and share for the fractional niche itself are unknown, and the proxy may grow at a different rate.",
         "Nothing will publish this directly; a bottom-up estimate (number of $2M-$20M firms x adoption rate x average retainer) built from Census SUSB plus buyer interviews."),
        ("No report gives market share for the fractional niche", "The only shares printed are for the Big Four and a few global firms (of management consulting or of CPA accounting); First Research prints none. "
         "None of those firms is a competitor for $2M-$20M clients in the way a fractional CFO boutique or platform would be.", SIGNAL_SOURCES["S2"]),
        ("Reports do not line up with the chosen code", rel, "Buy or access a report whose stated code matches the chosen NAICS, or one on a niche named 'outsourced accounting/CFO services'."),
        ("Mixed and dated vintages", f"Publication dates: {dates}. The First Research printout also embeds valuation multiples last updated January 2023 and an economic indicator dated May 2026 inside a report whose data was published July 2025.",
         "Re-pull each report at analysis time and record the publication date next to each number."),
        ("No pricing, retainer or margin data for the niche", "None of the seven signals covers what fractional CFOs charge or earn; the IBISWorld profit margins are for whole industries.",
         "Interviews and public rate cards; AICPA / trade compensation surveys."),
        ("Verification proves quotes exist, not that they were understood", "Code confirmed each quote is on its cited page. It cannot confirm that the LLM's summary, its choice of 'biggest' trend/threat, or its reading of a table row is right.",
         "A human reading the spot-check list against the PDFs (see the method section)."),
    ]
    for title, missing, find in structural:
        gaps.append({"scope": "structural", "signal_id": None, "doc_id": None, "why": title, "what_is_missing": missing, "what_would_find_it": find})
    return gaps

GAPS = stage5_gaps(EXTRACTIONS, VERIFIED, RECORDS, DOCS)
by_scope = collections.Counter(g["scope"] for g in GAPS)
print("Gaps:", dict(by_scope), "| total", len(GAPS), "\n")
for g in GAPS:
    if g["scope"] in ("document-signal", "signal"):
        print(f"[{g['signal_id']}] {g['doc_id']}: {g['why']}\n     missing: {textwrap.shorten(g['what_is_missing'], 150)}")
print("\nStructural gaps:")
for g in GAPS:
    if g["scope"] == "structural": print(" -", g["why"])
